name: "Setup KinD"
description: "Step to start and configure Kind"

inputs:
  k8s_version:
    description: "The Kubernetes version to use for the Kind cluster"
    required: false
    default: "v1.34.0"
  cluster_name:
    description: "Provide kind cluster name. Default is mlflow."
    required: false
    default: 'mlflow'

runs:
  using: "composite"
  steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.12.0
      id: cluster-create
      with:
        cluster_name: ${{ inputs.cluster_name }}
        kubectl_version: ${{ inputs.k8s_version }}
        version: v0.29.0
        node_image: kindest/node:${{ inputs.k8s_version }}
        registry: true

    - name: Retry Create k8s Kind Cluster
      uses: helm/kind-action@v1.12.0
      if: ${{ steps.cluster-create.outcome == 'failure' }}
      with:
        cluster_name: ${{ inputs.cluster_name }}
        kubectl_version: ${{ inputs.k8s_version }}
        version: v0.29.0
        node_image: kindest/node:${{ inputs.k8s_version }}
        registry: true
