apiVersion: batch/v1
kind: Job
metadata:
  name: init-seaweedfs
spec:
  template:
    spec:
      containers:
        - name: init-seaweedfs
          env:
            - name: S3_SCHEME
              value: "https"
