apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mlflow{{ .Values.resourceSuffix }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- if .Values.garbageCollection.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.garbageCollection.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mlflow-gc{{ .Values.resourceSuffix }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.garbageCollection.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.traceArchival.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.traceArchival.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mlflow-trace-archival{{ .Values.resourceSuffix }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.traceArchival.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
