name: Verify Manifest Builds

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/**'
      - 'config/**'
      - 'charts/**'
      - 'Makefile'

jobs:
  verify-builds:
    name: Verify kustomize and Helm builds
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: 'v3.14.0'

      - name: Verify manifests
        run: make verify-manifests
